//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailFee
    {
        public int Id { get; set; }
        public Nullable<int> IdFee { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
    
        public virtual Fee Fee { get; set; }
        public virtual User User { get; set; }
    }
}
