//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportBook
    {
        public int Id { get; set; }
        public Nullable<int> IdBook { get; set; }
        public Nullable<int> IdBookStore { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual BookStore BookStore { get; set; }
    }
}
